version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  scraper:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
