service: AbilityDraft

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - events:PutRule
      Resource:
        - *

functions:
  hello:
    handler: handler.hello


